#
# Example of a Dockerfile that extends the ml-python-image to add additional
# Python dependencies.
#
FROM fusion-dev-docker.ci-artifactory.lucidworks.com/ml-python-image:latest

USER root

RUN pip install torch

USER 8764
